export const AUTHOR_NAME = "Christian Vadalà"
export const AUTHOR_ROLE = "React.js & Node.js open source developer"
export const AUTHOR_LOCATION = "Rome, Italy, Europe, Earth"
export const LINK_WEBSITE = 'https://chrvadala.github.io'
export const LINK_GH = 'https://github.com/chrvadala'
export const LINK_NPM = 'https://www.npmjs.com/~chr.vadala'
export const LINK_LINKEDIN = "https://www.linkedin.com/in/chrvadala"
export const LINK_PAYPAL = "https://www.paypal.me/chrvadala/15"
export const LINK_GH_SPONSOR = "https://github.com/sponsors/chrvadala"