name: Continuous Delivery

on:
  push: ["develop"]

env:
  RUNNER_TEMP: /tmp

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: v12

      - name: Setup cache
        uses: actions/cache@v1
        id: yarn-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install --production

      - name: Build website
        run: yarn build

      - name: Publish on gh-pages
        run: |
          yarn global add gh-pages
          _BIN=$(yarn global dir)/node_modules/.bin
          ls $_BIN
          echo $_BIN
          $_BIN/gh-pages \
            --dist "$GITHUB_WORKSPACE/build" \
            --branch master \
            --repo "https://x-access-token:$GH_TOKEN@github.com/chrvadala/chrvadala.github.io" \
            --user "$GH_USER"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_USER: ${{secrets.USER }}
