name: Continuous Integration

on: ["push"]

env:
  RUNNER_TEMP: /tmp

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: v12

      - name: Setup cache
        uses: actions/cache@v1
        id: yarn-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install --production

      - name: Build website
        run: yarn build

      - name: Publish Artifact
        uses: actions/upload-artifact@v1
        with:
          name: Website
          path: build
