on: [push]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Setup cache
        uses: actions/cache@v1
        id: yarn-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install

      - name: Build website
        run: yarn build

      - name: Publish Artifact
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: build

  cd:
    name: CD
    runs-on: ubuntu-latest
    needs: [ci]
    steps:
      - uses: actions/checkout@v2

      - name: Download Artifact
        uses: actions/download-artifact@v1
        with:
          name: build
          path: build

      - name: Install gh-pages
        run: yarn global add gh-pages

      - name: Publish on gh-pages
        run: |
          _BIN=$(yarn global dir)/node_modules/.bin
          ls $_BIN
          echo $_BIN
          $_BIN/gh-pages \
            --dist "$GITHUB_WORKSPACE/build" \
            --branch master \
            --repo "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/chrvadala/chrvadala.github.io" \
            --user "$GH_USER"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_USER: ${{secrets.USER }}

