name: Release

on:
  push:
    branches:
      - sources

jobs:
  build:
    runs-on: ubuntu-18.04
    outputs:
      version: ${{ env.VERSION }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn install
      - run: yarn build
      - uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: build

  release:
    name: Release
    runs-on: ubuntu-18.04
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v1
        with:
          name: artifact
          path: build
      - name: Publish on gh-pages
        run: |
          yarn global add gh-pages
          _BIN=$(yarn global dir)/node_modules/.bin
          ls $_BIN
          echo $_BIN
          $_BIN/gh-pages \
            --dist "$GITHUB_WORKSPACE/build" \
            --branch master \
            --repo "https://x-access-token:$GH_TOKEN@github.com/chrvadala/chrvadala.github.io" \
            --user "$GH_USER"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_USER: ${{secrets.USER }}
