name: Test

on:
  - push
  - pull_request

jobs:
  build:
    name: Test Nodejs
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn install
      - run: yarn build
